version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - data:/app/data
      - static:/app/static
      - media:/app/media
    environment:
      - DEBUG=False
      - SECRET_KEY=your-secret-key-here-change-this-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DATABASE_PATH=/app/data/db.sqlite3
      - DJANGO_SETTINGS_MODULE=giftmanager.settings
    restart: unless-stopped
    container_name: giftmanager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
  static:
  media:
