# Generated by Django 5.1.3 on 2024-11-28 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_alter_gift_user_claimed_alter_user_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='family',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gifts.family'),
        ),
    ]
