# Generated by Django 5.2.4 on 2025-07-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0006_alter_gift_user_claimed_alter_user_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gift',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
