# Generated by Django 5.2.17 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0006_alter_gift_user_claimed_alter_user_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
