# Generated by Django 6.1 on 2026-08-30 16:07

import django.db.models.deletion
import gifts.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0008_gift_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='couple_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couple_gifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gift',
            name='link',
            field=models.TextField(blank=True, null=True, validators=[gifts.validators.UnlimitedURLValidator()]),
        ),
    ]
